# Autograd in PyTorch

In [24]:
import torch

Imagine we have some tensor $x$

In [25]:
x = torch.randn(3)
x

tensor([-0.1870, -0.6371, -0.2070])

Now imagine that we know that we want to calculate the gradient of a function wrt $x$ later on, then we would need to specify the following: 

In [26]:
x = torch.randn(3, requires_grad=True)
x

tensor([ 0.4718,  1.8963, -1.5208], requires_grad=True)

In [27]:
y = 3

In [28]:
z = 5

Now PyTorch will track the gradient of $x$ whenever do perform operations on this tensor! PyTorch will create a computational graph. 

<center><img 
     src="im3.jpg" 
     align="center" 
     width="300" 
/></center>

In [29]:
U = x * y
print(U)

tensor([ 1.4153,  5.6890, -4.5624], grad_fn=<MulBackward0>)


Here we see that $U$ has the **grad_fn** attribute **MulBackward** because here our operation was a multiplication. Let's do some additional operations!

<center><img 
     src="02_imgs/im4.png" 
     align="center" 
     width="450" 
/></center>

In [30]:
V = z + U
print(V)

tensor([ 6.4153, 10.6890,  0.4376], grad_fn=<AddBackward0>)


Here we see that the new torch tensor $V$ has the **grad_fn** attribute **AddBackward** because here our operation was an addition. Let's perform one last operation.

<center><img 
     src="02_imgs/im7.png" 
     align="center" 
     width="530" 
/></center>

In [31]:
J = V.mean()
print(J)

tensor(5.8473, grad_fn=<MeanBackward0>)


## Calculating Gradients 

Here we can calculate the gradients of each tensor wrt our initial input tensor $x$. Because we specified **requires_grad=True** for our initial tensor $X$, PyTorch has maintained a computational graph that we can access by calling the **backward()** method on any of the tensors in the graph. 

In [32]:
# compute dJ/dx
J.backward()

In [33]:
print(x.grad)

tensor([1., 1., 1.])


Here we see the gradients of $J$ wrt $x$. 