# Introduction to PyTorch Tensors

This simple notebook introduces PyTorch tensors and shows how to convert back and forth between torch tensors and numpy arrays. 

**Sources:**
- [Patrick Loeber](https://www.patrickloeber.com/)  
- [PyTorch Turorials - Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)  
- [Pytorch General Guide](https://pytorch.org/tutorials/beginner/basics/intro.html)


### Imports

In [51]:
import torch 
import numpy as np

### Scalar torch tensor

First lets create a torch tensor containing a scalar value

In [2]:
x = torch.empty(1)
x

tensor([0.])

### 1D torch tensor

Lets now create a vector, similar to a numpy array with shape [n,1] or shape [n,]

In [4]:
x = torch.empty(5)
x.round()

tensor([0., 0., 0., 0., 0.])

### 2D torch tensor

Let's create a 2D torch tensor, similar to a 2D numpy array:

In [5]:
x = torch.empty(3, 4)
x.round()

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### 3D torch tensor

Let's also examine a 3D torch tensor, commonly used when processing image data

In [6]:
x = torch.empty(2, 2, 3)
x.round()

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

### 4D torch tensor

We can generate torch tensors with even higher dimensions such as a 4D torch tensor: 

In [15]:
x = torch.empty(2, 2, 2, 3)
x.round()

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])

### Random tensors

Similar to numpy, we can also generate matrices containing random values

The values are drawn from a uniform distribution over the interval $[0, 1)$

In [18]:
x = torch.rand(3, 4)
x

tensor([[0.8393, 0.7594, 0.9819, 0.7015],
        [0.5948, 0.1297, 0.1648, 0.3865],
        [0.6259, 0.3575, 0.8722, 0.2854]])

### Tesnsors filled with a single value

Again similar to numpy we can generate a tensor filled with a single value

In [19]:
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### Altering the dtype in the tensor

We can also specifgy the data type for the data stored in a torch tensor

In [23]:
x = torch.ones(2, 3, dtype=torch.int32)
print(x)

y = torch.ones(2, 3, dtype=torch.float16)
print(y)

z = torch.ones(2, 3, dtype=torch.float64)
print(z)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


### Obtain the size of a torch tensor

This is very similar to numpy array's shape() method

In [24]:
x = torch.ones(2, 3, dtype=torch.int32)
print(x.size())

torch.Size([2, 3])


### Generating a tensor from a python list

In [25]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


# Tensor Operations

We can now add, subtract, divide, and multiply our torch tensors. 

We'll see how to apply both **element-wise** and **matrix** multiplication.

In [36]:
# addition
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y             #  <-- These two lines achieve the same thing
z = torch.add(x, y)   #  <-- These two lines achieve the same thing
print(z)

tensor([[0.1095, 0.0481],
        [0.0902, 0.0897]])
tensor([[0.8459, 0.7318],
        [0.5451, 0.9822]])
tensor([[0.9554, 0.7800],
        [0.6354, 1.0719]])


In [37]:
# subtraction
z = x - y                  #  <-- These two lines achieve the same thing
z = torch.subtract(x, y)   #  <-- These two lines achieve the same thing
print(z)

tensor([[-0.7364, -0.6837],
        [-0.4549, -0.8925]])


### in-place operations

Notice here how we can use **add_()** to do an in-place addition. Notice the trailing underscore here? Every operations in pytorch with a trailing underscore makes the update inplace. 

In [38]:
# in-place addition
y.add_(x)  # <-- updates y inplace
print(y)

tensor([[0.9554, 0.7800],
        [0.6354, 1.0719]])


In [39]:
# in-place subtraction
y.subtract_(x)  # <-- updates y inplace
print(y)

tensor([[0.8459, 0.7318],
        [0.5451, 0.9822]])


### Tensor multiplication

**Element-wise multiplication**

In [45]:
# element-wise multiplication
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = torch.multiply(x, y)   #  <-- These two lines achieve the same thing
z = x * y                  #  <-- These two lines achieve the same thing
print(z)

tensor([[0.1169, 0.1922],
        [0.4562, 0.6737]])
tensor([[0.0578, 0.8853],
        [0.7563, 0.9064]])
tensor([[0.0068, 0.1701],
        [0.3450, 0.6106]])


**Element-wise division**

In [49]:
# element-wise division
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = torch.div(x, y)        # <-- These two lines achieve the same thing
z = x / y                  #  <-- These two lines achieve the same thing
print(z)

tensor([[0.6204, 0.1772],
        [0.1047, 0.8120]])
tensor([[0.8453, 0.9869],
        [0.0296, 0.5976]])
tensor([[0.7339, 0.1795],
        [3.5387, 1.3589]])


**Matrix Multiplication**

In [50]:
# element-wise division
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

# matrix multiplication
z = torch.matmul(x, y)
print(z)

tensor([[0.9782, 0.8518],
        [0.4955, 0.0309]])
tensor([[0.5914, 0.9452],
        [0.2539, 0.8429]])
tensor([[0.7947, 1.6425],
        [0.3009, 0.4944]])
