# Introduction to PyTorch Tensors

This simple notebook introduces PyTorch tensors and shows how to convert back and forth between torch tensors and numpy arrays. 

**Sources:**
- [Patrick Loeber](https://www.patrickloeber.com/)  
- [PyTorch Turorials - Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)  
- [Pytorch General Guide](https://pytorch.org/tutorials/beginner/basics/intro.html)


### Imports

In [1]:
import torch 
import numpy as np

### Scalar torch tensor

First lets create a torch tensor containing a scalar value

In [2]:
x = torch.empty(1)
x

tensor([0.])

### 1D torch tensor

Lets now create a vector, similar to a numpy array with shape [n,1] or shape [n,]

In [3]:
x = torch.empty(5)
x.round()

tensor([0., 0., 0., 0., 0.])

### 2D torch tensor

Let's create a 2D torch tensor, similar to a 2D numpy array:

In [4]:
x = torch.empty(3, 4)
x.round()

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### 3D torch tensor

Let's also examine a 3D torch tensor, commonly used when processing image data

In [5]:
x = torch.empty(2, 2, 3)
x.round()

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

### 4D torch tensor

We can generate torch tensors with even higher dimensions such as a 4D torch tensor: 

In [6]:
x = torch.empty(2, 2, 2, 3)
x.round()

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])

### Random tensors

Similar to numpy, we can also generate matrices containing random values

The values are drawn from a uniform distribution over the interval $[0, 1)$

In [7]:
x = torch.rand(3, 4)
x

tensor([[0.1216, 0.1669, 0.8774, 0.8541],
        [0.7493, 0.9617, 0.3434, 0.2318],
        [0.3335, 0.3350, 0.1434, 0.7950]])

### Tesnsors filled with a single value

Again similar to numpy we can generate a tensor filled with a single value

In [8]:
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### Altering the dtype in the tensor

We can also specifgy the data type for the data stored in a torch tensor

In [9]:
x = torch.ones(2, 3, dtype=torch.int32)
print(x)

y = torch.ones(2, 3, dtype=torch.float16)
print(y)

z = torch.ones(2, 3, dtype=torch.float64)
print(z)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


### Obtain the size of a torch tensor

This is very similar to numpy array's shape() method

In [10]:
x = torch.ones(2, 3, dtype=torch.int32)
print(x.size())

torch.Size([2, 3])


### Generating a tensor from a python list

In [11]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


# Tensor Operations

We can now add, subtract, divide, and multiply our torch tensors. 

We'll see how to apply both **element-wise** and **matrix** multiplication.

In [12]:
# addition
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y             #  <-- These two lines achieve the same thing
z = torch.add(x, y)   #  <-- These two lines achieve the same thing
print(z)

tensor([[0.1188, 0.4462],
        [0.2256, 0.8137]])
tensor([[0.8763, 0.9261],
        [0.8501, 0.5577]])
tensor([[0.9951, 1.3723],
        [1.0757, 1.3714]])


In [13]:
# subtraction
z = x - y                  #  <-- These two lines achieve the same thing
z = torch.subtract(x, y)   #  <-- These two lines achieve the same thing
print(z)

tensor([[-0.7576, -0.4800],
        [-0.6245,  0.2561]])


### in-place operations

Notice here how we can use **add_()** to do an in-place addition. Notice the trailing underscore here? Every operations in pytorch with a trailing underscore makes the update inplace. 

In [14]:
# in-place addition
y.add_(x)  # <-- updates y inplace
print(y)

tensor([[0.9951, 1.3723],
        [1.0757, 1.3714]])


In [15]:
# in-place subtraction
y.subtract_(x)  # <-- updates y inplace
print(y)

tensor([[0.8763, 0.9261],
        [0.8501, 0.5577]])


### Tensor multiplication

**Element-wise multiplication**

In [16]:
# element-wise multiplication
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = torch.multiply(x, y)   #  <-- These two lines achieve the same thing
z = x * y                  #  <-- These two lines achieve the same thing
print(z)

tensor([[0.5092, 0.6067],
        [0.5029, 0.4416]])
tensor([[0.9853, 0.8399],
        [0.2461, 0.4486]])
tensor([[0.5017, 0.5096],
        [0.1238, 0.1981]])


**Element-wise division**

In [17]:
# element-wise division
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = torch.div(x, y)        # <-- These two lines achieve the same thing
z = x / y                  #  <-- These two lines achieve the same thing
print(z)

tensor([[0.4379, 0.8128],
        [0.8643, 0.8964]])
tensor([[0.0581, 0.9350],
        [0.5061, 0.1077]])
tensor([[7.5406, 0.8693],
        [1.7077, 8.3244]])


**Matrix Multiplication**

In [18]:
# element-wise division
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

# matrix multiplication
z = torch.matmul(x, y)
print(z)

tensor([[0.5507, 0.1333],
        [0.9063, 0.2442]])
tensor([[0.9043, 0.9480],
        [0.2478, 0.9752]])
tensor([[0.5310, 0.6520],
        [0.8801, 1.0973]])


## Slicing Operations

In [19]:
x = torch.rand(5, 3)
x

tensor([[0.0338, 0.8825, 0.6898],
        [0.2414, 0.0794, 0.8200],
        [0.3991, 0.0100, 0.0542],
        [0.1904, 0.8649, 0.7281],
        [0.6408, 0.2784, 0.7436]])

Similar to Numpy, we can slide the 2D array to retrieve only the first column

In [21]:
# print the first column
print(x[:, 0])

tensor([0.0338, 0.2414, 0.3991, 0.1904, 0.6408])


In [22]:
# print the first row
print(x[0, :])

tensor([0.0338, 0.8825, 0.6898])


In [25]:
# index an individual value
print(x[2, 1])

tensor(0.0100)


In [28]:
# here we can return the floating point value from the torch tensor contining a single value
print(x[2, 1].item())

0.009952843189239502


In [29]:
print(type(x[2, 1]))
print(type(x[2, 1].item()))

<class 'torch.Tensor'>
<class 'float'>


## Reshaping Tensors

In [31]:
x = torch.rand(4, 4)
x

tensor([[0.6595, 0.9184, 0.4075, 0.2779],
        [0.4833, 0.5294, 0.6674, 0.4318],
        [0.6629, 0.0059, 0.9440, 0.4606],
        [0.8884, 0.9520, 0.1222, 0.1521]])

In [32]:
# reshape x into a tensory (y) with new dimensions
y = x.view(16)
y

tensor([0.6595, 0.9184, 0.4075, 0.2779, 0.4833, 0.5294, 0.6674, 0.4318, 0.6629,
        0.0059, 0.9440, 0.4606, 0.8884, 0.9520, 0.1222, 0.1521])

In [35]:
# here we can reshape to a tensor of shape (8, 2) and we can let PyTorch retrieve the value for the number of columns (2)
y = x.view(8, -1)
y

tensor([[0.6595, 0.9184],
        [0.4075, 0.2779],
        [0.4833, 0.5294],
        [0.6674, 0.4318],
        [0.6629, 0.0059],
        [0.9440, 0.4606],
        [0.8884, 0.9520],
        [0.1222, 0.1521]])

In [40]:
print(f'Original shape: {x.size()}')
print(f'New shape: {y.size()}')

Original shape: torch.Size([4, 4])
New shape: torch.Size([8, 2])


## Converting between PyTorch tensors and Numpy arrays 

In [41]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [42]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [43]:
print(type(a))
print(type(b))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


### NOTE: be careful here because a and b will share the same space in memory!! 

If we create a torch tensor called 'a' and then create a numpy array called 'b' using a.numpy(), then modifying 'a' will also modify 'b' 

In [48]:
a = torch.ones(5)
b = a.numpy()

print(f'Old torch tensor: {a}')
print(f'Old numpy array: {b}')

b *= 2

print(f'New torch tensor: {a}')
print(f'New numpy array: {b}')

Old torch tensor: tensor([1., 1., 1., 1., 1.])
Old numpy array: [1. 1. 1. 1. 1.]
New torch tensor: tensor([2., 2., 2., 2., 2.])
New numpy array: [2. 2. 2. 2. 2.]


So we can see where that modifying the array 'b' also modified the tensor 'a'

**NOTE** This memory sharing does NOT occur if you're using GPU memory for torch tensors

In [50]:
torch.cuda.is_available()

False

We can see here that cuda is not available, so PyTorch is relying only on CPU memory for storing torch tensors. Ergo, the numpy array copy of a torch tensor will share memory with the tensor itself. 

## Utilizing CUDA and GPUs

In [51]:
if torch.cuda.is_available():
    print('CUDA is available!')

Here we see that CUDA is not available. If it were, however, we could create a tensor on the GPU and then bring it back to CPU memory

In [52]:
if torch.cuda.is_available():
    print('CUDA is available!')
    
    # define the GPU device 
    device = torch.device("cuda")
    
    # store x as a torch tensor in GPU memory
    x = torch.ones(5, device=device)
    
    # store y as a tensor in CPU memory and then move it over to GPU memory
    y = torch.ones(5)
    y.to(device)
    
    # perform an operation using the GPU (very fast!!)
    z = x + y
    
    # be careful here... we need to move the 'z' tensor back to CPU memory before we can store it as a numpy array
    z.to("cpu")
    
    # and now we can store z as a numpy array in CPU memory
    z_np = z.numpy()

## Using 'requires_grad'

In [54]:
x = torch.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

This stores the gradients of this tensor as we perform operations on the tensor. We will need this to be true (requires_grad=True) for any variable that we want to optimize. 